### ISSUE TITLE
Cannot install 2.1.3 on Dart SDK 1.24.2

### ISSUE THREAD

**Issue by patorash** [accorto/lightning-dart#53]
I wrote "lightning" in pubspec.yaml.

```yaml
environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  lightning: ^2.1.3
```

And execute `pub get`, but not install lightning 2.1.3.

```bash
pub get
Resolving dependencies...
Package lightning has no versions that match >=2.1.3 <3.0.0 derived
exit code 1
```
